name: Buf CI
on:
  push:
  pull_request:
    types:
      # Defaults
      - opened
      - synchronize
      - reopened
      # Retrigger with buf-specific labels
      - labeled
      - unlabeled
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@main
        with:
          username: ${{ secrets.BUF_USERNAME }}
          token: ${{ secrets.BUF_TOKEN }}
